### ISSUE TITLE
Unable to install PE using PIM on Windows

### ISSUE THREAD

**Issue by cwebster61083** [puppetlabs/puppet-enterprise_issues#4]
## Describe the Bug
When using PIM on Windows, I get a permission denied error when it tries to create `/etc/puppetlabs` on my installation target. 

I am using the same user and ssh key used in our support lab, so I suspect there is an issue with how Bolt is configured to make the ssh connection. 

I did attempt to recreate what we are doing in our lab provisioned by creating an inventory.yaml file in the `.BProject` folder, but it gets deleted as soon as the installer starts. Below is the contents of the inventory.yaml. 

```
config:
  transport: ssh
  ssh:
    host-key-check: false
    run-as: root
    user: user
    private-key: ~/.ssh/id_rsa-acceptance
```

## Expected Behavior
PE should be installed without getting a permission error. 

## Steps to Reproduce

On a fresh Windows node with no previously configured SSH configs, run through the PIM installer using only the SSH user and key for that user. 

## Environment
 - Windows 2019
 - Google Cloud
 - PE 2023
 - RHEL 7

![image](https://github.com/puppetlabs/puppet-enterprise_issues/assets/50930031/a61bc2cf-4f50-45c7-8d56-b89f2edc62ae)

**Comment by cwebster61083** [comment]
Using the following, I can use the parameter file generated by PIM with PEADM. The `--run-as root` allowed it to progress through where it failed before. 

```
PS C:\Users\user\Downloads\puppet-installation-manager-v1.0.0-windows\.BProject> bolt plan run peadm::install --params @C:\Users\user\Downloads\puppet-installation-manager-v1.0.0-windows\data\fail_install_20240222_184021.json --no-ssl-verify --no-host-key-check --private-key C:\Users\user\.ssh\id_rsa-acceptance --run-as root
```

**Comment by cwebster61083** [comment]
Adding the following to `bolt-defaults.yaml` under `C:\Users\user\.puppetlabs\etc\bolt` also resolved the issue. 

```
inventory-config:
  transport: ssh
  ssh:
    host-key-check: false
    run-as: root
    user: user
    private-key: ~/.ssh/id_rsa-acceptance
```
We may want to add some options in the wizard to be able to pass `--run-as` to the bolt plan command that gets used to do the install.
